version: '3'

services:
  web:
    build: ./messgapi
    restart: always
    container_name: messg-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./messgapi/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    networks:
      - web

networks:
  web:
    driver: bridge
